### ISSUE TITLE
Link preview points to content that doesn't exist anymore

### ISSUE THREAD

**Issue by aymannadeem** [aymannadeem/yourhaq#11]
![image](https://cloud.githubusercontent.com/assets/875834/22437452/01d36398-e6dd-11e6-8510-b128c4895ca3.png)

**Comment by jgblight** [comment]
<img width="1003" alt="screen shot 2017-01-30 at 1 58 23 pm" src="https://cloud.githubusercontent.com/assets/2576935/22443593/470615f2-e6f4-11e6-8f09-1f1171065699.png">

Facebook Crawler has since updated the preview. It's also possible to force-update it here: https://developers.facebook.com/tools/debug/

**Comment by irishbryan** [comment]
Resolved in https://github.com/aymannadeem/yourhaq/commit/be4f744307b5dcf8baf45336c01636630326e742
