### ISSUE TITLE
Vision Page - Left justify paragraphs

### ISSUE THREAD

**Issue by hamberguesa** [aymannadeem/yourhaq#30]
Best practice would be to left justify the two paragraphs on the vision page. Centered text reduces usability and slows down readers (speed and comprehension). Happy to submit a PR for this!

**Comment by dmleong** [comment]
I agree with you @hamberguesa that it's a bit hard to read, but I think an small redesign of the page might be helpful, in addition to changing the alignment. (the footer alignment is also funky)

Since the page is very wide, the text is getting stretched out, making it hard to read. What do you think of doing a 2x2 grid here? 

|   |   |
|---|---|
| Content here  | Connect people  |
| Build a record  | Content here  |

**Comment by dmleong** [comment]
@jglover this might be a useful thing to address in your mocks from here https://github.com/aymannadeem/yourhaq/issues/24
